[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://cupons-desconto.vercel.app"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
